# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
# orbs:
#   docker: circleci/docker@1.4.0

jobs:
  build:
    docker:
      - image: docker:latest
    steps: 
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker build -t conformance/base:latest -f .circleci/Dockerfile .
          docker push conformance/base:latest
  kind: 
    docker:
      - image: conformance/base:latest
    steps: 
      - checkout
      - run: |
          echo "test"
# Orchestrate or schedule a set of jobs
workflows:
  test:
    jobs:
      - build
      - kind:
          requires:
            - build
