# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
# orbs:
#   docker: circleci/docker@1.4.0

jobs:
  build:
    docker:
      - image: docker:latest
    steps: 
      - setup_remote_docker:
          docker_layer_caching: false
      - checkout
      - run: |
          docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
          docker build -t conformance/base:latest -f .circleci/Dockerfile .
          docker push conformance/base:latest

  cnf_conformance: 
    docker:
      - image: conformance/base:test
    working_directory: /mnt/ramdisk
    steps: 
      - setup_remote_docker
      - checkout
      - run: |
          kind create cluster
          shards install  
          LOG_LEVEL=info crystal spec spec/cnf_conformance_spec.cr -v

# Orchestrate or schedule a set of jobs
workflows:
  test:
    jobs:
      - build
      - cnf_conformance:
          requires:
            - build
