# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
# orbs:
#   docker: circleci/docker@1.4.0

jobs:
  build_docker:
    docker:
      - image: docker:latest
    steps: 
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - run: docker build -f .circleci/Dockerfile . 
  build_vm:
    machine:
      docker_layer_caching: true
    steps:
      - checkout
      - run: docker build -f .circleci/Dockerfile . 
# Orchestrate or schedule a set of jobs
workflows:
  test:
    jobs:
      - build_docker
      - build_vm
