apiVersion: v1
kind: Pod
metadata:
    name: reboot
spec:
  containers:
  - name: reboot
    image: conformance/reboot_daemon:latest
    command: ["/entrypoint.sh"]
    volumeMounts:
    - mountPath: /sysrq
      name: sysrq-volume
  volumes:
  -  name: sysrq-volume
     hostPath:
       path: /proc/sysrq-trigger
