name: Crystal Specs
on: [push, pull_request]
jobs:
  spec:
    name: Crystal Specs
    runs-on: ubuntu-latest
    strategy:
      matrix:
        spec_file: ["spec/prereqs_spec.cr", "spec/setup_spec.cr"]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install Clusterctl
      run: |
        curl -L https://github.com/kubernetes-sigs/cluster-api/releases/download/v0.3.10/clusterctl-linux-amd64 -o clusterctl
        chmod +x ./clusterctl
        sudo mv ./clusterctl /usr/local/bin/clusterctl
    - name: Install Crystal
      env:
        CRYSTAL_VERSION: 0.35.1
        CRYSTAL_URL: https://github.com/crystal-lang/crystal/releases/download
      run: |
        wget -O crystal.deb "$CRYSTAL_URL/$CRYSTAL_VERSION/crystal_$CRYSTAL_VERSION-1_amd64.deb" --progress=dot:giga; 
        sudo apt install -y --no-install-recommends \
        git \
        libssl-dev \
        libxml2-dev \
        libyaml-dev \
        libgmp-dev \
        libz-dev \
        ./crystal.deb \
        && sudo rm -rf /var/lib/apt/lists/*
    - name: Create Kind Cluster 
      run: |
        kind create cluster
        kubectl get nodes 
    - name: Setup CNF-Conformance
      run: |
        shards install  
        crystal src/cnf-conformance.cr setup
    - name: Run Crystal Spec
      run: |
        LOG_LEVEL=info crystal spec --warnings none ${{ matrix.spec_file }} -v
