name: Crystal CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: crystallang/crystal

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: shards install
    - name: Kind install
      run: |
        apt-get install curl
        apt-get install wget
        wget https://dl.google.com/go/go1.12.linux-amd64.tar.gz
        tar -xvf go1.12.linux-amd64.tar.gz
        sudo mv go /usr/local
        export GOROOT=/usr/local/go
        export GOPATH=$HOME/go
        export PATH=$GOPATH/bin:$GOROOT/bin:$PATH
        curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
        GO111MODULE=on go get sigs.k8s.io/kind
        kind create cluster
        export KUBECONFIG="$(kind get kubeconfig-path)"
    - name: Run tests
      run: crystal spec
