name: Crystal CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: crystallang/crystal

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: shards install
    - name: Kind install
      shell: bash
      run: |
        apt-get update && apt-get install -y curl && apt-get install -y wget && wget https://dl.google.com/go/go1.12.linux-amd64.tar.gz && tar -xvf go1.12.linux-amd64.tar.gz && mv go /usr/local && \
        echo "::set-env name=GOROOT::/usr/local/go" && \
        echo "::set-env name=GOPATH::${{ github.workspace }}/go" && \
        echo "::set-env name=PATH::$GOPATH/bin:$GOROOT/bin:$PATH" && \
        curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl && chmod +x kubectl && mv kubectl /usr/local/bin/ && \
        GO111MODULE=on go get sigs.k8s.io/kind && \
        curl -Lo kind https://github.com/kubernetes-sigs/kind/releases/download/0.0.1/kind-linux-amd64 && chmod +x kind && mv kind /usr/local/bin/ && \
        kind create cluster && \
        echo "::set-env name=KUBECONFIG::$(kind get kubeconfig-path)"
    - name: Run tests
      run: crystal spec
